package de.rwth.idsg.bikeman.app.exception;


public enum AppErrorCode {
    NOT_REGISTERED,
    AUTH_FAILED,
    CONSTRAINT_FAILED,
    RENTAL_BLOCKED,
    BOOKING_BLOCKED,
    VALIDATION_FAILED,
    AUTH_ATTEMPTS_EXCEEDED,
    DATABASE_OPERATION_FAILED,
    UNKNOWN_SERVER_ERROR
}
